using System;

//namespace _16.Exception
//{
//    class Throw
//    {
//        static void DoSomething(int arg)
//        {
//            if (arg < 10)
//                Console.WriteLine($"arg : {arg}");
//            else
//                throw new System.Exception("arg가 10보다 큽니다.");
//        }
//        static void Main(string[] args)
//        {
//            try
//            {
//                DoSomething(1);
//                DoSomething(3);
//                DoSomething(5);
//                DoSomething(7);
//                DoSomething(9);
//                DoSomething(11); // 예외 발생
//                DoSomething(13); // 예외가 이미 발생하여 실행되지 않음
//            }
//            catch (System.Exception e)
//            {
//                Console.WriteLine(e.Message);
//            }
//        }
//    }
//}
